//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_User
    {
        public int ID { get; set; }
        public Nullable<int> ID_Application { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
    }
}
