//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatUser
    {
        public int ID { get; set; }
        public Nullable<int> IDChat { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDLastReadMess { get; set; }
    
        public virtual Chatt Chatt { get; set; }
        public virtual Chatt Chatt1 { get; set; }
        public virtual Messagee Messagee { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
