//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messagee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Messagee()
        {
            this.ChatUser = new HashSet<ChatUser>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDChat { get; set; }
        public Nullable<int> IDUserSend { get; set; }
        public Nullable<int> TextMessage { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
    
        public virtual Chatt Chatt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatUser> ChatUser { get; set; }
        public virtual User User { get; set; }
    }
}
