//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoApplication
    {
        public int ID { get; set; }
        public string Photo { get; set; }
        public Nullable<int> IDApplicatioon { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
